### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by averyanalex** [esanchezm/prometheus-qbittorrent-exporter#11]
Is there way to export https qbittorrent host?

**Comment by esanchezm** [comment]
Hi @averyanalex, I'm not sure to understand what you want. Can you be more specific or give me an example? Thanks!

**Comment by averyanalex** [comment]
My qbittorent behind nginx reverse proxy (with ssl). But if I set host to *****.**, and port to 443, I get error "plain http request sent to https port"

**Comment by esanchezm** [comment]
Ok, I understand. Well, you should run this exporter in the same network where qbittorrent is running. I don't know if you can do it, but that's what you should do.

However, I think I can work on SSL support, can't promise anything but I'll work on it :smile:

**Comment by averyanalex** [comment]
Thanks, now I connect exporter directly to qbittorrent as a workaround

**Comment by esanchezm** [comment]
Will be fixed in #35
