### ISSUE TITLE
Publish image to GHCR

### ISSUE THREAD

**Issue by onedr0p** [esanchezm/prometheus-qbittorrent-exporter#12]
Dockerhub rate limits are a pita, it would be cool if you could push this image to the github container registry. It's not hard to do.

Thanks!

**Comment by esanchezm** [comment]
I'm sorry but this was already set up [some time ago](https://github.com/esanchezm/prometheus-qbittorrent-exporter/commit/a9a3e5d1e66cdead456eb2655144507bc1c2b5bf). The documentation doesn't reflect it, but I just tried it and it's working:

```bash

$ docker pull ghcr.io/esanchezm/prometheus-qbittorrent-exporter                                                                           root@nas 16:40:10
Using default tag: latest

latest: Pulling from esanchezm/prometheus-qbittorrent-exporter
Digest: sha256:dd6c1c638e60abe88b58feb8ded5578d0a3cc746417958573f6fbd44a7dc0c9b
Status: Downloaded newer image for ghcr.io/esanchezm/prometheus-qbittorrent-exporter:latest
ghcr.io/esanchezm/prometheus-qbittorrent-exporter:latest
```

Feel free to change your container references, I'll try to update the doc to reflect it

**Comment by onedr0p** [comment]
You need to make it public

```
❯ docker pull ghcr.io/esanchezm/prometheus-qbittorrent-exporter
Using default tag: latest
Error response from daemon: failed to resolve reference "ghcr.io/esanchezm/prometheus-qbittorrent-exporter:latest": failed to authorize: failed to fetch anonymous token: unexpected status: 401 Unauthorized
```

**Comment by onedr0p** [comment]
Find the package over at https://github.com/esanchezm?tab=packages and make it public please 👍🏼

**Comment by esanchezm** [comment]
@onedr0p thanks! It's public now 😄
