### ISSUE TITLE
Grafana dashboard doesn't work with v8 or Kubernetes deoloys

### ISSUE THREAD

**Issue by chrisjohnson00** [esanchezm/prometheus-qbittorrent-exporter#17]
There are some changes in v8 that seem to make the dashboard not work anymore.  I'm creating this issue after the fact (I've fixed it), so I don't have specifics, sorry.  I do remember that the `$DS_PROMETHEUS` input wouldn't work for me.

Also, the dashboard was created with the expectation that the container name never changes.  However, in a Kubernetes deployment, the container name only lasts as long as the container is running, so it results in multiple series of data being displayed when the container is replaced, which isn't what is intended for some of the panels.

**Comment by esanchezm** [comment]
Fixed. Thanks for your cooperation @chrisjohnson00 !
