### ISSUE TITLE
Metrics should have a qbittorrent_ prefix

### ISSUE THREAD

**Issue by Gabisonfire** [esanchezm/prometheus-qbittorrent-exporter#2]
Metrics should be prepended with `qbittorrent_` for clarity and to follow `https://prometheus.io/docs/practices/naming/`.

I have multiple application I'm collecting and qbittorrent's ones are scattered because of this.

I can make a PR later to fix this but wanted to ask here first. Cheers!

**Comment by esanchezm** [comment]
Hi @Gabisonfire,

Yeah, that's something that was on the back on my mind and I actually had some code to do that but I discarded it in the end. I think I can recover it and push it.

Thanks!

**Comment by esanchezm** [comment]
Fixed in eee65ec.
