### ISSUE TITLE
[Feature Request] All-Time

### ISSUE THREAD

**Issue by JAKAMI99** [esanchezm/prometheus-qbittorrent-exporter#22]
Would it be possible to include the (All-time) "upload", "download" and "share ratio" which is shown under View>Statistics in the Web UI?
Or is the used python module not supporting those values. 
Sadly, I was not able to dig into the python code from the module to check if my request is obsolete.

Thanks for the project <3

**Comment by JAKAMI99** [comment]
The All-Time feature was added in 2013 trough this commitment:
https://github.com/qbittorrent/qBittorrent/pull/1105

maybe this helps :)

**Comment by crazyuploader** [comment]
Was wondering about the same! It'd be nice to have that stats as well :)

**Comment by esanchezm** [comment]
Fixed in #34. Thank you all and sorry for the delay :)
