### ISSUE TITLE
Tags for the last two releases not publish to docker registry

### ISSUE THREAD

**Issue by esprimo** [esanchezm/prometheus-qbittorrent-exporter#28]
It seems the recent versions aren't published to the docker registry.

```console
$ docker pull esanchezm/prometheus-qbittorrent-exporter:v1.3.0
Error response from daemon: manifest for esanchezm/prometheus-qbittorrent-exporter:v1.3.0 not found: manifest unknown: manifest unknown

$ docker pull esanchezm/prometheus-qbittorrent-exporter:v1.4.0
Error response from daemon: manifest for esanchezm/prometheus-qbittorrent-exporter:v1.4.0 not found: manifest unknown: manifest unknown

$ podman search --list-tags esanchezm/prometheus-qbittorrent-exporter                                       
NAME                                                 TAG
docker.io/esanchezm/prometheus-qbittorrent-exporter  latest
docker.io/esanchezm/prometheus-qbittorrent-exporter  master
docker.io/esanchezm/prometheus-qbittorrent-exporter  v1.0.1
docker.io/esanchezm/prometheus-qbittorrent-exporter  v1.0.2
docker.io/esanchezm/prometheus-qbittorrent-exporter  v1.1.0
docker.io/esanchezm/prometheus-qbittorrent-exporter  v1.1.1
docker.io/esanchezm/prometheus-qbittorrent-exporter  v1.2.0
```

I would appreciate if tags for the new releases were also published!

For what it's worth, `:latest` and `:master` seem to be updated, but I'd still prefer version tags for releases. That way I can use for example Renovate or Dependabot to get alerted about updates. I also assume versioned releases are considered more stable than continuously following master.

**Comment by buroa** [comment]
Same with ghcr.io/esanchezm/prometheus-qbittorrent-exporter

**Comment by esanchezm** [comment]
Apologies for this, I'll take a look

**Comment by esprimo** [comment]
I can see `1.4.0` there now at least!

```console
$ podman search --list-tags esanchezm/prometheus-qbittorrent-exporter
NAME                                                 TAG
docker.io/esanchezm/prometheus-qbittorrent-exporter  1.4.0
docker.io/esanchezm/prometheus-qbittorrent-exporter  latest
docker.io/esanchezm/prometheus-qbittorrent-exporter  master
docker.io/esanchezm/prometheus-qbittorrent-exporter  v1.0.1
docker.io/esanchezm/prometheus-qbittorrent-exporter  v1.0.2
docker.io/esanchezm/prometheus-qbittorrent-exporter  v1.1.0
docker.io/esanchezm/prometheus-qbittorrent-exporter  v1.1.1
docker.io/esanchezm/prometheus-qbittorrent-exporter  v1.2.0
```

**Comment by esanchezm** [comment]
Yeah but that's buggy as it's not keeping the `v` prefix as others.

Latest release v1.4.0 should be both in [docker hub](https://hub.docker.com/repository/docker/esanchezm/prometheus-qbittorrent-exporter/general) and [GHCR registry](https://github.com/esanchezm/prometheus-qbittorrent-exporter/pkgs/container/prometheus-qbittorrent-exporter/versions?filters%5Bversion_type%5D=tagged).

I won't be publishing old releases nor the `master` tag anymore

**Comment by perryhuynh** [comment]
Sorry to necro this but it looks like the latest release was still pushed with the `master` tag

**Comment by buroa** [comment]
Just noticed this as well. `v1.5.0` was not pushed to ghcr.io @esanchezm

**Comment by esanchezm** [comment]
I think it's fixed now 😄 Thanks for your support and interest in this small project 🤗

**Comment by buroa** [comment]
@esanchezm Looks great and it deployed [fine](https://github.com/buroa/k8s-gitops/pull/1738); thanks!
