### ISSUE TITLE
Question about this software

### ISSUE THREAD

**Issue by fett1979** [esanchezm/prometheus-qbittorrent-exporter#33]
Sorry, i try to reach via X but, i can't message directly...
So.. i have multiple clients.
How i can handle 5-6 clients at the same times
All clients are qbittorrent installed on Ubuntu.
Thank you.

**Comment by esanchezm** [comment]
Hey @fett1979 thanks for your interest and for reaching out. This is totally the best option to contact.

There's no a support for multiple hosts and also the host label is not added to the metrics. So, the only way I can think now is to have multiple exporters running with different settings, especially the `METRICS_PREFIX` to identify each of the servers. It would be something like:


*Exporter 1 for server 1*

```
METRICS_PREFIX=qbittorent1
QBITTORRENT_HOST=my.qbittorrent1.server.com
```

*Exporter 2 for server 2*

```
METRICS_PREFIX=qbittorent2
QBITTORRENT_HOST=another.qbittorrent2.server.com
```

This is far from ideal and I think I should add the server labels to identify each of the metrics. That should be easy to do...

**Comment by esanchezm** [comment]
I've added a new `server` label so in theory you should be able to run many exporters with just changing the `QBITTORRENT_HOST` variable. A new release is coming but you could use `latest` version
