### ISSUE TITLE
export only some metrics

### ISSUE THREAD

**Issue by milahu** [esanchezm/prometheus-qbittorrent-exporter#50]
export only some metrics to reduce cpu load

(would that help to reduce cpu load?)

i only need `alltime_dl_total` and `alltime_ul_total`
(or `dl_info_data` and `up_info_data` if faster)

### possible solution

```sh
#!/bin/sh
export METRICS_INCLUDE=alltime_dl_total,alltime_ul_total
exec qbittorrent-exporter
```

**Comment by esanchezm** [comment]
Hello! Could you show me proof of CPU usage for this exporter? Mine has been running for years and I've never noticed any huge usage caused by the exporter

**Comment by esanchezm** [comment]
I'm sorry but I don't see enough rationale behind it. Yeah, the exporter makes different API calls, but that's probably less than the web UI. I'd be happy to take a further look if I get faced with metrics supporting the high CPU usage
