### ISSUE TITLE
URL DNS?

### ISSUE THREAD

**Issue by thewho2018** [esanchezm/prometheus-qbittorrent-exporter#74]
Hi!

I'm trying to setup a exporter to use my DNS url. Reason is to be able to use my wildcard SSL certificate. It might just be me doing something incorrectly but i wanted to verify that it actually should work?

**Comment by esanchezm** [comment]
So you want the exporter to use your DNS server to resolve, is that correct?

If that's the case, you shouldn't do anything else as it will use the network setup you have and if the host is using these DNS, the exporter will use them too.
